
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import os
from pathlib import Path
import pyglet

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,ttk
import subprocess
pyglet.font.add_file("C:/Users/user/PycharmProjects/pythonProject2/Myfont.ttf")
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\user\PycharmProjects\pythonProject2\build\assets\frame0")
def login(username,password):
    if username == "" and password == "":
        print("Please, print username and password")
    elif username == "" or password == "":
        print("Please, print second position")
    else:
        window.destroy()

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("587x558")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 558,
    width = 587,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    587.0,
    214.0,
    fill="#3B1E4A",
    outline="")

canvas.create_rectangle(
    0.0,
    214.0,
    587.0,
    596.0,
    fill="#FFFFFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: login(entry_4.get(),entry_2.get()),
    relief="flat"
)
button_1.place(
    x=183.0,
    y=462.0,
    width=222.0,
    height=61.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_4 = canvas.create_image(
    294.0,
    278.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#E2E2E2",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=46.0,
    y=260.0,
    width=496.0,
    height=34.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    294.0,
    349.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#E2E2E2",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=46.0,
    y=331.0,
    width=496.0,
    height=34.0
)

canvas.create_text(
    45.0,
    306.0,
    anchor="nw",
    text="Password\n",
    fill="#000000",
    font=("Inter", 16 * -1)
)

canvas.create_text(
    45.0,
    236.0,
    anchor="nw",
    text="Username\n",
    fill="#000000",
    font=("Inter", 16 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    316.0,
    88.0,
    image=image_image_1
)

canvas.create_text(
    83.0,
    150.0,
    anchor="nw",
    text="TerrIToriumcraft\n",
    fill="#FFFFFF",
    font=("Myfont", 40)
)
window.resizable(False, False)
window.mainloop()
