# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import ttk
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import subprocess
import minecraft_launcher_lib
from uuid import uuid1
from random_username.generate import generate_username

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\user\PycharmProjects\pythonProject2\build\assets\frame1")

minecraft_directory = minecraft_launcher_lib.utils.get_minecraft_directory().replace('minecraft',"meshlauncher")
versions = [version["id"] for version in minecraft_launcher_lib.utils.get_version_list()]

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("587x558")
window.configure(bg = "#3B1E4A")
def run(version,username):
    if version not in versions:
        print("Please, select version")
    else:
        minecraft_launcher_lib.install.install_minecraft_version(versionid=version,
                                                                minecraft_directory=minecraft_directory)

        options = {
            "username": username,
            "uuid": str(uuid1()),
            "token": ""
        }
        subprocess.call(minecraft_launcher_lib.command.get_minecraft_command(version=version,
                                                                             minecraft_directory=minecraft_directory,
                                                                             options=options))


canvas = Canvas(
    window,
    bg = "#3B1E4A",
    height = 558,
    width = 587,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    58.0,
    7.0,
    anchor="nw",
    text="TerrIToriumcraft\n",
    fill="#FFFFFF",
    font=("Itim Regular", 25 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    549.0,
    34.0,
    image=image_image_1
)
image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    282.0,
    164.0,
    image=image_image_2
)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    294.0,
    360.0,
    image=entry_image_1
)
entry_1 = ttk.Combobox(
    value=versions,
    background="#B0B0B0",
    foreground="#000716",
)
entry_1.place(
    x=35.0,
    y=340.0,
    width=530.0,
    height=45.0
)

canvas.create_text(
    36.0,
    318.0,
    anchor="nw",
    text="Version\n\n",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)


button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: run(entry_1.get(),"User"),
    relief="flat"
)
button_1.place(
    x=183.0,
    y=449.0,
    width=222.0,
    height=61.0
)

window.resizable(False, False)
window.mainloop()
